name: Build and Push Docker Image to ECR

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      image_tag:
        required: false
        type: string
        default: latest
      dockerfile:
        required: false
        type: string
        default: ./Dockerfile
      notify_slack:              
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:         
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build tag and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repository }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f ${{ inputs.dockerfile }} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Output image URL
        run: |
          echo "Image pushed:${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}"

      - name: Notify Slack Status (styled)
        if: ${{ inputs.notify_slack && always() }}
        run: |
          STATUS="${{ job.status }}"
          COLOR="#36a64f" # verde
          if [ "$STATUS" != "success" ]; then
            COLOR="#ff0000" # vermelho
          fi

          WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          REPO_URL="https://github.com/${{ github.repository }}"

          LOGS_URL="http://k8s-monitori-promethe-d54735ffe4-1157155869.us-east-1.elb.amazonaws.com/a/grafana-lokiexplore-app/explore?from=now-1h&to=now&var-ds=P8E80F9AEF21F6940&var-filters=&patterns=%5B%5D&timezone=browser&var-primary_label=service_name%7C%3D~%7C.%2B&var-fields=&var-levels=&var-metadata=&var-all-fields=&var-patterns=&var-lineFilterV2=&var-lineFilters=&var-filters_replica="
          ARGO_URL="https://argo.paymode.weareglobals.com"

          PAYLOAD=$(cat <<EOF
          {
            "attachments": [
              {
                "color": "$COLOR",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "üöÄ Pipeline Finalizado"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Status:*\n*$STATUS*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Tag:*\n${{ inputs.image_tag }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Reposit√≥rio:*\n<$REPO_URL|${{ github.repository }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Branch:*\n${{ github.ref_name }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Autor:*\n${{ github.actor }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:*\n${{ github.sha }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "‚ö†Ô∏è *Observa√ß√£o Importante:*\n‚Ä¢ Se voc√™ usa a tag *latest*, lembre que precisa reiniciar a app no cluster.\n‚Ä¢ Se voc√™ usa vers√£o, lembre de trocar a vers√£o no \`deployment.yaml\` e tamb√©m no caminho \`./.github\` dentro do workflow do seu pipe."
                    }
                  },
                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üîç Ver Pipeline"
                        },
                        "url": "$WORKFLOW_URL"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üìÅ Ver Reposit√≥rio"
                        },
                        "url": "$REPO_URL"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üî• Ver Logs"
                        },
                        "url": "$LOGS_URL"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üöÄ Ver Argo"
                        },
                        "url": "$ARGO_URL"
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )

          curl -X POST -H "Content-type: application/json" \
            --data "$PAYLOAD" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

