name: Build and Push Docker Image to ECR

on:
  workflow_call:
    inputs:
      aws_region:
        required: true
        type: string
      ecr_repository:
        required: true
        type: string
      image_tag:
        required: false
        type: string
        default: latest
      dockerfile:
        required: false
        type: string
        default: ./Dockerfile
      use_codeartifact:
        required: false
        type: boolean
        default: false
      notify_slack:              
        required: false
        type: boolean
        default: false
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      SLACK_WEBHOOK_URL:         
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.aws_region }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # S√≥ roda se use_codeartifact = true
      - name: Get CodeArtifact token
        id: codeartifact
        if: ${{ inputs.use_codeartifact }}
        run: |
          TOKEN=$(aws codeartifact get-authorization-token \
            --domain paymode-development \
            --domain-owner 975050328856 \
            --region ${{ inputs.aws_region }} \
            --query authorizationToken \
            --output text)
          echo "CODEARTIFACT_AUTH_TOKEN=$TOKEN" >> $GITHUB_ENV

      - name: Build, tag, and push image to ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.ecr_repository }}
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          BUILD_ARGS=""
          if [ "${{ inputs.use_codeartifact }}" = "true" ]; then
            echo "CodeArtifact token enabled"
            BUILD_ARGS="--secret id=codeartifact_token,env=CODEARTIFACT_AUTH_TOKEN"
          fi

          docker build $BUILD_ARGS \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
            -f ${{ inputs.dockerfile }} .

          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Output image URL
        run: |
          echo "Image pushed: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.ecr_repository }}:${{ inputs.image_tag }}"


      - name: Notify Slack Status (styled)
        if: ${{ inputs.notify_slack && always() }}
        run: |
          STATUS="${{ job.status }}"
          COLOR="#36a64f" # verde
          if [ "$STATUS" != "success" ]; then
            COLOR="#ff0000" # vermelho
          fi

          WORKFLOW_URL="https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          REPO_URL="https://github.com/${{ github.repository }}"

          PAYLOAD=$(cat <<EOF
          {
            "attachments": [
              {
                "color": "$COLOR",
                "blocks": [
                  {
                    "type": "header",
                    "text": {
                      "type": "plain_text",
                      "text": "üöÄ Pipeline Finalizado"
                    }
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Status:*\n*$STATUS*"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Tag:*\n${{ inputs.image_tag }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Reposit√≥rio:*\n<$REPO_URL|${{ github.repository }}>"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Branch:*\n${{ github.ref_name }}"
                      }
                    ]
                  },
                  {
                    "type": "section",
                    "fields": [
                      {
                        "type": "mrkdwn",
                        "text": "*Autor:*\n${{ github.actor }}"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*Commit:*\n${{ github.sha }}"
                      }
                    ]
                  },

                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "‚ö†Ô∏è *Observa√ß√£o Importante:*\n‚Ä¢ Se voc√™ usa a tag *latest*, lembre que precisa **restartar a app no cluster**.\n‚Ä¢ Se voc√™ usa *vers√£o*, lembre de **trocar a vers√£o no \`deployment.yaml\`** e tamb√©m no caminho **\`./.github\` dentro do workflow do seu pipe**."
                    }
                  },

                  {
                    "type": "actions",
                    "elements": [
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üîç Ver Pipeline"
                        },
                        "url": "$WORKFLOW_URL"
                      },
                      {
                        "type": "button",
                        "text": {
                          "type": "plain_text",
                          "text": "üìÅ Ver Reposit√≥rio"
                        },
                        "url": "$REPO_URL"
                      }
                    ]
                  }
                ]
              }
            ]
          }
          EOF
          )

          curl -X POST -H "Content-type: application/json" \
            --data "$PAYLOAD" \
            ${{ secrets.SLACK_WEBHOOK_URL }}

